# Generated by Django 3.0.8 on 2020-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, upload_to='upload', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
